### ISSUE TITLE
What is necessary to build a wheel?

### ISSUE THREAD

**Issue by gaylong9** [shashankx86/dlib_compiled#1]
Thanks a lot for your wheel. 
I can easily build a wheel by `pip install dlib` on my windows10 laptop. But on my another new computer,  it dose not work. 
I try to make the environment on both sides the same, including cmake, boost and vs2019.
So, could you share your experience about building a wheel? Or what is necessary to build a wheel?

**Comment by shashankx86** [comment]
Thanks a lot for your wheel.:- Thanks

I can easily build a wheel by pip install dlib on my windows10 laptop.: Some of people don't have much knowledge or they can't download lots of thing so I compiled it for those people 
 
So, could you share your experience about building a wheel?: Piece of cake for me, Nice!

what is necessary to build a wheel?: Nope, I compiled it just from those people don't have much knowledge or they can't download lots of thing

**Comment by gaylong9** [comment]
Thanks for reply.
I can`t build the wheel on my another new computer, although I tried to make the environments the same.
So I wonder what softwares, packages or skills you used?

**Comment by shashankx86** [comment]
> So I wonder what softwares, packages or skills you used?

Just Cmd/terminal and some knowledge 

Search on Google you will get lots of blogs and articles I used those

**Comment by gaylong9** [comment]
`pip install dlib -v`
I compared verbose between tow computers, and found `error C2734: “GifAsciiTable8x8”`.
After searching related blogs, I solved the error and successfully installed dlib.
Thanks again!
