### ISSUE TITLE
I installed it but when I run the app that I work on I have the following issue 

### ISSUE THREAD

**Issue by aljanabi00** [shashankx86/dlib_compiled#2]
`from _dlib_pybind11 import *
ImportError: DLL load failed while importing _dlib_pybind11: A dynamic link library (DLL) initialization routine failed.`

**Comment by shashankx86** [comment]
> `from _dlib_pybind11 import * ImportError: DLL load failed while importing _dlib_pybind11: A dynamic link library (DLL) initialization routine failed.`

Ask on https://github.com/davisking/dlib
