### ISSUE TITLE
dlib-19.22.99-cp39-cp39-win_amd64.whl is not a supported wheel on this platform. (ubuntu, python 3.9.9)

### ISSUE THREAD

**Issue by soufianechalouh** [shashankx86/dlib_compiled#4]

**Comment by soufianechalouh** [comment]
When I follow the instructions, I get this error: 

> dlib-19.22.99-cp39-cp39-win_amd64.whl is not a supported wheel on this platform

I'm inside a venv. python version: 3.9.9. OS: Ubuntu

**Comment by shashankx86** [comment]
> When I follow the instructions, I get this error:
> 
> > dlib-19.22.99-cp39-cp39-win_amd64.whl is not a supported wheel on this platform
> 
> I'm inside a venv. python version: 3.9.9. OS: Ubuntu

use this https://github.com/sachadee/Dlib
